##### The cell below is for you to keep track of the libraries used and install those libraries quickly
##### Ensure that the proper library names are used and the syntax of `%pip install PACKAGE_NAME` is followed

In [ ]:
%pip install pandas 
%pip install matplotlib
# add commented pip installation lines for packages used as shown above for ease of testing
# the line should be of the format %pip install PACKAGE_NAME

## **DO NOT CHANGE** the filepath variable
##### Instead, create a folder named 'data' in your current working directory and 
##### have the .csv file inside that. A relative path *must* be used when loading data into pandas

In [2]:
# Can have as many cells as you want for code
import pandas as pd
filepath = "./data/catA_train.csv" 
# the initialised filepath MUST be a relative path to a folder named data that contains the parquet file

### **ALL** Code for machine learning and dataset analysis should be entered below. 
##### Ensure that your code is clear and readable.
##### Comments and Markdown notes are advised to direct attention to pieces of code you deem useful.

In [3]:
###...code...###
#Read data 
df = pd.read_csv(filepath)

In [ ]:
print(df.info())

In [28]:
#### Handling Missing Values ####
df.isna().sum()/len(df)
#Employees (Single Site)                0.425022
#Import/Export Status                   0.773388
#Fiscal Year End                        0.769139
#Square Footage                         1.000000
#The 4 Columns above have too many missing values and loses their significance in the analysis;
#Imputation will be difficult and inaccurate due to the lack of data
#Therefore they should be removed
##df1: removed useless columns
columns = ['Employees (Single Site)','Import/Export Status','Fiscal Year End','Square Footage']
df1 = df.drop(columns = columns)
n_null = df1.isnull().sum(axis=1)
missing_info = pd.DataFrame({
    'Number_of_Missing_Values': n_null,
    'Has_Missing_Values': n_null > 0
})
missing_info.describe()
##based on the info shown, the vast majority of the rest of the rows have no missing values. 
#It is safe to remove any row with missing values without impacting the result significantly
##df2: removed rows with missing values
df2 = df1.dropna()
df2.isnull().sum()
df2.describe()

,LATITUDE,LONGITUDE,SIC Code,8-Digit SIC Code,Year Found,Employees (Domestic Ultimate Total),Employees (Global Ultimate Total),Sales (Domestic Ultimate Total USD),Sales (Global Ultimate Total USD),Is Domestic Ultimate,Is Global Ultimate
count,24868.000000,24868.000000,24868.000000,2.486800e+04,24868.000000,24868.000000,2.486800e+04,2.486800e+04,2.486800e+04,24868.000000,24868.000000
mean,1.320456,103.843496,6180.363318,6.180134e+07,2004.480859,140.285709,6.773448e+03,8.091866e+08,3.335261e+09,0.494129,0.294716
std,0.043637,0.053674,1696.570099,1.696493e+07,13.611786,1122.568965,4.449997e+04,1.096728e+10,1.880385e+10,0.499976,0.455924
min,1.238792,103.611319,132.000000,1.320000e+06,1819.000000,1.000000,1.000000e+00,-1.502631e+08,1.000000e+00,0.000000,0.000000
25%,1.284665,103.831986,5084.000000,5.084070e+07,1997.000000,4.000000,4.000000e+00,1.026308e+06,1.026308e+06,0.000000,0.000000
50%,1.309011,103.848989,6719.000000,6.719000e+07,2008.000000,15.000000,1.500000e+01,2.550017e+06,2.696300e+06,0.000000,0.000000
75%,1.337750,103.865922,7219.000000,7.219000e+07,2015.000000,60.000000,1.000000e+02,1.975387e+07,1.050800e+08,1.000000,1.000000
max,1.469800,104.003218,9721.000000,9.721990e+07,2023.000000,80000.000000,2.190000e+06,3.184764e+11,5.140000e+11,1.000000,1.000000

## The cell below is **NOT** to be removed
##### The function is to be amended so that it accepts the given input (dataframe) and returns the required output (list). 
##### It is recommended to test the function out prior to submission
-------------------------------------------------------------------------------------------------------------------------------
##### The hidden_data parsed into the function below will have the same layout columns wise as the dataset *SENT* to you
##### Thus, ensure that steps taken to modify the initial dataset to fit into the model are also carried out in the function below

In [11]:
def testing_hidden_data(hidden_data: pd.DataFrame) -> list:
    '''DO NOT REMOVE THIS FUNCTION.

The function accepts a dataframe as input and return an iterable (list)
of binary classes as output.

The function should be coded to test on hidden data
and should include any preprocessing functions needed for your model to perform. 
    
All relevant code MUST be included in this function.'''

    result = [] 
    return result

##### Cell to check testing_hidden_data function

In [ ]:
# This cell should output a list of predictions.
test_df = pd.read_csv(filepath)
test_df = test_df.drop(columns=['Sales (Domestic Ultimate Total USD)'])
print(testing_hidden_data(test_df))

### Please have the filename renamed and ensure that it can be run with the requirements above being met. All the best!